const sampleJson = {
	userStats: [
		{
			playerName: "あさぴっぴ1020",
			steamID: "STEAM_0:1:485188694",
			perk: "KFGame.KFPerk_Gunslinger",
			playTime: 191.4201,
			damageDealt: 4854,
			damageTaken: 0,
			healsGiven: 0,
			healsReceived: 0,
			doshEarned: 464,
			shotsFired: 74,
			shotsHit: 56,
			headShots: 48,
			deaths: 0,
			weaponDamages: [Array],
			zedKills: [Object],
		},
	],
	matchInfo: {
		timeStamp: "2024/10/17 - 22:31:10",
		mapName: "KF-SubSynth",
		serverName: "",
		serverIP: "",
		isVictory: false,
		defeatWave: 1,
		cheatMessages: [],
		mutators: [
			"FriendlyHUD.FriendlyHUDMutator",
			"FriendlyHUD.FriendlyHUDCDCompatController",
			"CombinedCD2.xVotingHandler",
		],
		isSolo: true,
		CDInfo: {
			spawnCycle: "basic_light",
			maxMonsters: 60,
			cohortSize: 0,
			spawnPoll: 1,
			waveSizeFakes: 1,
			spawnMod: 0,
			trashHPFakes: 6,
			QPHPFakes: 6,
			FPHPFakes: 6,
			SCHPFakes: 6,
			ZTSpawnMode: "clockwork",
			ZTSpawnSlowDown: 1.5,
			albinoAlphas: false,
			albinoCrawlers: false,
			albinoGorefasts: false,
			disableRobots: false,
			disableSpawners: false,
			fleshpoundRageSpawns: false,
			startWithFullAmmo: false,
			startWithFullArmor: false,
			startWithFullGrenade: false,
			zedsTeleportCloser: false,
		},
	},
};
